import Head from 'next/head'
import NavBar from '../components/NavBar'


export default function Home() {
  return (
    <>
      <Head>
        <title>Comboni Health</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon.ico" />
      </Head>
      <NavBar />
    </>
  )
}
